device: 0

#deepsort
config_deepsort: settings/deep_sort.yaml
deep_sort_weights: models/ckpt.t7

#yolo
yolo_weights: best1.pt
agnostic_nms: false
augment: false
classes: [1, 2, 3, 5, 7]
conf_thres: 0.35
imgsz: [416]
iou_thres: 0.5
max_det: 1000
dnn: false
evaluate: false
half: false
visualize: false
firebase : true
came_name: cam1

#in-out
fourcc: mp4v
source: vehiclecam1.MOV
#source: 'http://192.168.1.12:8160/'
output: inference/output
save_csv: true
save_txt: false
save_vid: false
show_vid: true

#lines zones
upper_ratio: 0.4
lower_ratio: 0.9231

#DB
upload_db: false

#deep_sort_pytorch/configs/deep_sort.yaml
#../settings/deep_sort.yaml
#../../video_nhax_cut_resize2.mp4
#deep_sort_weights: deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7