# Generated by Django 3.2.13 on 2022-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclespeed',
            name='speed',
            field=models.FloatField(default=0, null=True),
        ),
    ]
